Static library product
siteline/SwiftUI-Introspect pull request #168
Opened 2022-09-27 17:18 UTC by krzyzanowskim

Resolves #159 

This workaround Xcode Cloud builds (due to longstanding Xcode Cloud bug that can't build and link dynamic dependency properly)

2022-09-28 06:11 UTC, jegumhon approved these changes

2022-11-15 11:32 UTC, krzyzanowskim commented
who's in power to merge it?

2023-02-03 13:14 UTC, davdroman requested changes

2023-02-03 13:14 UTC, davdroman commented on Package.swift
>          )
I don't think we can accept such a big breaking change. Though the following might be acceptable:

```suggestion
        .library(name: "Introspect", targets: ["Introspect"]),
        .library(name: "Introspect-Static", type: .static, targets: ["Introspect"]),
        .library(name: "Introspect-Dynamic", type: .dynamic, targets: ["Introspect"]),
```

Libraries like [PhoneNumberKit](https://github.com/marmelroy/PhoneNumberKit/blob/master/Package.swift#L10-L12) take the same approach.

2023-02-03 13:17 UTC, davdroman commented
@SplittyDev let me know if this solution looks sensible to you.

2023-02-03 16:05 UTC, SplittyDev commented
@davdroman Generally looks good to me. I'm not sure whether the static entry is needed, though. Afaik, static linkage is the default in Swift, so adding an entry for dynamic linkage should be enough to provide both. Providing both `Introspect` and `Introspect-Static` shouldn't be necessary, unless I'm missing something.

2023-02-03 16:07 UTC, krzyzanowskim commented
@SplittyDev `static` is the whole point of this change because automatically it happen to go dynamic and Xcode build fail

> Xcode Cloud bug that can't build and link dynamic dependency

2023-02-03 16:31 UTC, davdroman commented
Great stuff. I'll merge this as soon as the CircleCI situation is sorted.

2023-02-03 17:13 UTC, SplittyDev commented
> @SplittyDev `static` is the whole point of this change because automatically it happen to go dynamic and Xcode build fail
> 
> > Xcode Cloud bug that can't build and link dynamic dependency

You're absolutely right, I got this wrong at first. Great change, thanks for the PR!

2023-02-07 13:23 UTC, davdroman approved these changes

2023-02-10 17:23 UTC, davdroman commented
@krzyzanowskim #179 should be fixed now. Can you push an empty commit to retrigger the CI please?

2023-02-10 17:55 UTC, joelpoloney commented
This is no longer blocked by CircleCI FYI.

2023-02-10 18:16 UTC, merged

2023-02-14 09:28 UTC, davdroman commented
Hi @krzyzanowskim. 0.2.0 is now out and includes this change. Please let us know at some point whether this fixed your Xcode Cloud issues. Thanks!