Add GitHub action
siteline/SwiftUI-Introspect pull request #78
Opened 2021-03-12 21:33 UTC by SplittyDev

2021-03-12 23:45 UTC, SplittyDev commented
Seems like this is working now, however a very small amount of tests takes longer than a second and even _rarely_ fails with a 2s timeout. Not sure why this happens, but I guess in that case we can always just re-run the test.

For now I updated all tests to use a timeout of 2s, which should also help with sporadically failing CircleCI tests.

2021-03-13 03:03 UTC, JannThomas requested changes

2021-03-13 03:03 UTC, JannThomas commented on IntrospectTests/AppKitTests.swift
> +let TIMEOUT: TimeInterval = 2 // just to be really safe on CI
Can we use swift style guide syntax for this? Shouldn't be all uppercase and should probably be in an enum `Constants` inside `TestUtils` as a static let.

2021-03-13 03:03 UTC, JannThomas commented on .github/workflows/build-and-test.yml
> +        run: swift test -v
Can you add a newline at the end of the file?

2021-03-13 12:21 UTC, JannThomas approved these changes

2021-03-13 12:22 UTC, merged